Feat/met 5048 disable for maintenance
europeana/metis-ui pull request #793
Opened 2023-08-15 15:23 UTC by andyjmaclean

2023-09-13 07:58 UTC, jeortizquan requested changes
Tested locally and it works we need to take into account the caching time and the polling time so the maintenance message is displayed. just have an small observation about the field name.
![afbeelding](https://github.com/europeana/metis-ui/assets/19560266/979817ef-813a-4a66-8215-95cb227f989e)

2023-09-14 04:56 UTC, andyjmaclean commented on projects/sandbox/src/app/app.component.spec.ts
> +  const b4Each = (): void => {
`beforeEach` is a command so can't be reused as a variable name - that's why I use [b4each](url), here and throughout the projects.

2023-09-14 05:08 UTC, andyjmaclean commented on projects/metis/src/environments/maintenance-settings.ts
> +  pollInterval: 60000,
Milliseconds are assumed by default in all the front-end projects.  In Metis-UI alone we have:

```
-   intervalStatusShort: 1000,
-   intervalStatus: 2500,
-   intervalStatusMedium: 5000,
-   intervalStatusLong: 60000,
-   intervalStatusMax: 60000 * 9.5,

``` 
In JS generally milliseconds are assumed -  `new Date().getTime()` exists, but `new Date().getTimeInMilliseconds()` doesn't.

2023-09-14 05:08 UTC, andyjmaclean commented on projects/sandbox/src/environments/maintenance-settings.ts
> +  pollInterval: 60000,
Please see above.

2023-09-14 08:09 UTC, jeortizquan commented on projects/sandbox/src/app/app.component.spec.ts
> +  const b4Each = (): void => {
I see. thanks for the explanation.

2023-09-14 08:10 UTC, jeortizquan commented on projects/metis/src/environments/maintenance-settings.ts
> +  pollInterval: 60000,
my suggestion came from when reading the code is easier to remember what are the units of the variable.

2023-09-14 09:30 UTC, merged