Feat/met 5489 angular update
europeana/metis-ui pull request #803
Opened 2023-09-25 15:33 UTC by andyjmaclean

2023-09-28 08:00 UTC, jeortizquan reviewed
I see the process of updating to dependency injection. and a small suggestion for the sandbox.

2023-09-28 10:01 UTC, andyjmaclean commented on projects/sandbox/src/app/chart/pie/pie.component.html
> +    title="{{ pieDimension | formatTierDimension }} {{ item.text }}:    {{
You have a point, @jeortizquan, but this is configured in the ts and could maybe happen in a future ticket?

2023-09-28 16:24 UTC, andyjmaclean commented on package-lock.json
This is not a dependency that I specify directly in `package.json` but something flagged by the audit, and it's the norm that `npm audit` throws up this kind of thing.

The dependency comes from cypress so I ran ng update cypress, which takes it from version 10.x to version 16.x locally, but this creates issues I was not able to solve: 

![image](https://github.com/europeana/metis-ui/assets/4441899/516dd8af-2f87-4fc7-abe0-8e5b09ae2e70)
 
I was able to have the test run using `cypress@11.0`, but not `@^12.0` without encountering this issue. The `@cypress/request` warning is no longer present in the audit (but other things are).

2023-09-29 11:51 UTC, jeortizquan commented on package-lock.json
I took a look on it, here is a PR https://github.com/europeana/metis-ui/pull/804 to update to cypress `@^13.3.0` you can merge it into this current branch so the dependency is updated. please have a look.

2023-09-29 11:57 UTC, jeortizquan commented on projects/sandbox/src/app/chart/pie/pie.component.html
> +    title="{{ pieDimension | formatTierDimension }} {{ item.text }}:    {{
yes. I agree. I created this followup ticket to address this topic.
https://europeana.atlassian.net/browse/MET-5518

2023-09-29 12:00 UTC, jeortizquan requested changes
Please have a look to the suggested PR #804  . In the newest version of cypress the removed `cy.server()`, `cy.route()` https://docs.cypress.io/guides/references/changelog I have updated it using `cy.intercept()` and removed `cy.server()` that now is a default as they mention in the documentation.

2023-09-29 15:05 UTC, jeortizquan approved these changes

2023-10-03 09:47 UTC, jeortizquan reviewed
there are some suggestions for some name variables.

2023-10-03 09:47 UTC, jeortizquan commented on projects/metis/src/app/dataset/dataset.component.ts
> +  private readonly route = inject(ActivatedRoute);
`route` => `activatedroute`

2023-10-03 09:47 UTC, jeortizquan commented on projects/metis/src/app/dataset/datasetform/datasetform.component.ts
> +  private readonly fb = inject(NonNullableFormBuilder);
`fb` => `formbuilder`

2023-10-03 09:47 UTC, jeortizquan commented on projects/metis/src/app/dataset/depublication/depublication.component.ts
> +  private readonly fb = inject(NonNullableFormBuilder);
`fb`=>`formbuilder`

2023-10-03 09:47 UTC, jeortizquan commented on projects/metis/src/app/dataset/workflow/workflow.component.ts
> +  private readonly fb = inject(FormBuilder);
`fb`=> `formbuilder`

2023-10-03 09:49 UTC, jeortizquan reviewed
There are some suggestions for the name of some variables.

2023-10-03 12:33 UTC, andyjmaclean commented on projects/metis/src/app/dataset/workflow/workflow.component.ts
> +  private readonly fb = inject(FormBuilder);
Done (but camel-cased!)

2023-10-03 12:33 UTC, andyjmaclean commented on projects/metis/src/app/dataset/depublication/depublication.component.ts
> +  private readonly fb = inject(NonNullableFormBuilder);
Done (but camel-cased!)

2023-10-03 12:34 UTC, andyjmaclean commented on projects/metis/src/app/dataset/dataset.component.ts
> +  private readonly route = inject(ActivatedRoute);
Done (but camel-cased!)

2023-10-03 12:34 UTC, andyjmaclean commented on projects/sandbox/src/app/upload/upload.component.ts
> +  private readonly fb = inject(FormBuilder);
Done (but camel-cased!)

2023-10-03 12:34 UTC, andyjmaclean commented on projects/sandbox/src/app/sandbox-navigation/sandbox-navigation.component.ts
> +  private readonly fb = inject(NonNullableFormBuilder);
Done (but camel-cased!)

2023-10-05 22:49 UTC, merged