MET-6239 Add Debias Info
europeana/metis-ui pull request #865
Opened 2024-11-04 14:10 UTC by andyjmaclean

2024-11-06 16:55 UTC, jeortizquan requested changes
Test is failing 
![Sandbox -- Debias -- should toggle the info (failed)](https://github.com/user-attachments/assets/c9b0007e-db06-440e-ba4f-fa2ff6b80001)

2024-11-06 16:55 UTC, jeortizquan commented on projects/sandbox/src/app/debias/debias.component.html
![afbeelding](https://github.com/user-attachments/assets/09ec17a9-7a43-4388-af10-c9d02e987f8e)

2024-11-06 16:55 UTC, jeortizquan commented on projects/sandbox/src/app/debias/debias.component.html
is overlapping over the text I don't know if you desire this behaviour.

2024-11-06 16:55 UTC, jeortizquan commented on projects/sandbox/src/app/debias/dedias.component.spec.ts
filename rename `dedias` to `debias`

2024-11-07 18:35 UTC, andyjmaclean commented on projects/sandbox/src/app/debias/debias.component.html
Yes - that is the desired behaviour.

2024-11-07 19:01 UTC, andyjmaclean commented on projects/sandbox/src/app/debias/dedias.component.spec.ts
Done

2024-11-09 09:56 UTC, merged